name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REPO: "Advanced-OSINT-Framework-with-Claude-AI"
      AUTHOR: "FJ-CYBERZILLA"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Show build context
      run: |
        echo "🔍 Installing project: $REPO"
        echo "👤 Author: $AUTHOR"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Build ehunter.cpp
      run: |
        echo "⚡ Compiling source into 'ehunter'"
        g++ -std=c++17 -O2 -Wall -o ehunter ehunter.cpp

    - name: Run executable
      run: ./ehunter
